- name: Check if Metricbeat package is installed
  yum:
    list: installed
  register: yum_packages

- set_fact: 
    package_status: "{{yum_packages | json_query(jsonquery) | length }}"
  vars:
    jsonquery: "results[?name=='metricbeat']"

- name: install Packege {{beat}} if not exist
  yum:
    name: "{{beat}}"
    state: present
  when: package_status == "0" 